/**
 * CarboniX Configuration
 * Generated by: npx @carbonix/cli init
 * ─────────────────────────────────────────────────────────────────────────────
 * Set CARBONIX_API_KEY in your .env to override the key below.
 * Get your key from your CarboniX Dashboard → Settings → API Keys
 */
const Carbonix = require('carbonix').default;

const cx = new Carbonix({
  apiKey:  process.env.CARBONIX_API_KEY  || 'cbx_a9330cd412a45ad31b03531d69aa39777e5425c86704f778',
  baseUrl: process.env.CARBONIX_BASE_URL || 'https://api-production-f6965.up.railway.app',
  timeoutMs: 10_000,
});

module.exports = { cx };
