/**
 * CarboniX Configuration — generated by `npm install carbonix`
 * Set CARBONIX_API_KEY in your .env file.
 * Get your API key from your CarboniX Dashboard.
 */
const Carbonix = require('carbonix').default;

const cx = new Carbonix({
  apiKey:  process.env.CARBONIX_API_KEY  || 'cx_YOUR_API_KEY_HERE',
  baseUrl: process.env.CARBONIX_BASE_URL || 'http://localhost:4000',
  timeoutMs: 10_000,
});

module.exports = { cx };
